# Generated by Django 5.2.7 on 2025-10-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=20)),
                ('premios', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('id_tbmd', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Streaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sinopseCurta', models.TextField()),
                ('sinopseLonga', models.TextField()),
                ('duracaoMinutos', models.IntegerField()),
                ('atores', models.ManyToManyField(related_name='filmes', to='filmes.ator')),
                ('generos', models.ManyToManyField(related_name='filmes', to='filmes.genero')),
                ('streaming', models.ManyToManyField(related_name='filmes', to='filmes.streaming')),
            ],
        ),
    ]
