# Generated by Django 5.2.7 on 2025-10-27 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_avaliacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='duracaoMinutos',
            new_name='nota_media',
        ),
        migrations.AddField(
            model_name='filme',
            name='media_tmdb',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
