# Generated by Django 5.2.7 on 2025-10-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_rename_duracaominutos_filme_nota_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='lancamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
