# Generated by Django 5.2.7 on 2025-10-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_filme_lancamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='media_tmdb',
        ),
        migrations.RemoveField(
            model_name='genero',
            name='id_tbmd',
        ),
        migrations.AlterField(
            model_name='ator',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filme',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genero',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='streaming',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
