# Generated by Django 5.2.7 on 2025-10-29 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0005_remove_filme_media_tmdb_remove_genero_id_tbmd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='sinopseCurta',
            new_name='sinopse',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='sinopseLonga',
        ),
    ]
