# Generated by Django 5.2.7 on 2025-10-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0006_rename_sinopsecurta_filme_sinopse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='nota_media',
            field=models.FloatField(),
        ),
    ]
