# Generated by Django 5.2.7 on 2025-10-29 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0007_alter_filme_nota_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ator',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='ator',
            name='premios',
        ),
        migrations.RemoveField(
            model_name='ator',
            name='sexo',
        ),
    ]
