# Generated by Django 5.2.7 on 2025-10-29 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0008_remove_ator_idade_remove_ator_premios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streaming',
            name='link',
        ),
    ]
